version: "3"
services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "8887:8887"
        volumes:
            - "./mydonkey:/donkey/mydonkey"
